CREATE TYPE INVITATION_STATUS AS ENUM ('ACCEPTED', 'DECLINED', 'NEW');

CREATE TABLE IF NOT EXISTS invitation (
  id BIGSERIAL PRIMARY KEY,
  receiver_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  status INVITATION_STATUS DEFAULT 'NEW',
  created_at TIMESTAMP DEFAULT NOW(),

  FOREIGN KEY (receiver_id) REFERENCES "users" (id)
  MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (sender_id) REFERENCES "users" (id)
  MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,

  FOREIGN KEY (event_id) REFERENCES "event" (id)
  MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER SEQUENCE invitation_id_seq INCREMENT BY 50;